version: 0.2
phases:
  install:
    # Upewnij się, że to jest wcięte dwa razy
    runtime-versions:
      # Upewnij się, że to jest wcięte trzy razy
      nodejs: 20 
    # Upewnij się, że to jest wcięte dwa razy
    commands:
      # Linia 7: Dwie spacje przed myślnikiem, spacja po myślniku
      - echo "Instalacja: Node.js" 
      # Linia 8: Dwie spacje przed myślnikiem, spacja po myślniku
      - pip install aws-sam-cli 
  
  build:
    commands:
      - echo "Budowanie aplikacji SAM. Automatyczne pakowanie funkcji..."
      - sam build
  
  post_build:
    commands:
      - echo "Wdrażanie do AWS CloudFormation/Lambda..."
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name PlotAss-Backend-Stack --capabilities CAPABILITY_IAM

artifacts:
  files:
    - template.yaml
