version: 0.2
phases:
  install:
    runtime-versions:
      # Używamy Node.js 20.x, który jest kompatybilny z naszym kodem .mjs
      nodejs: 20 
    commands:
      - echo "Instalacja: Node.js"
  build:
    commands:
      - echo "Rozpoczynanie pakowania funkcji Lambda..."
      # WAŻNE: Komendy ZIP. Upewnij się, że ścieżka do backend/ jest poprawna.
      - zip -j ChapterManager.zip backend/ChapterManager.mjs
      - zip -j DashboardDataResolver.zip backend/DashboardDataResolver.mjs
      - zip -j LLM_QueryResolver.zip backend/LLM_QueryResolver.mjs
      - echo "Pakowanie zakończone. Utworzono artefakty ZIP."
artifacts:
  files:
    # Definicja artefaktów do wdrożenia
    - ChapterManager.zip
    - DashboardDataResolver.zip
    - LLM_QueryResolver.zip
