version: 0.2
phases:
  install:
    runtime-versions:
      # Używamy stabilnej wersji Node.js, która obsługuje .mjs
      nodejs: 20 
    commands:
      - echo "Instalacja: Node.js (bez npm install)"
  build:
    commands:
      - echo "Rozpoczynanie pakowania funkcji Lambda..."
      # WAŻNE: Używamy '-j' (junk paths), aby pliki trafiły do głównego katalogu ZIP.
      - zip -j ChapterManager.zip backend/ChapterManager.mjs
      - zip -j DashboardDataResolver.zip backend/DashboardDataResolver.mjs
      - zip -j LLM_QueryResolver.zip backend/LLM_QueryResolver.mjs
      - echo "Pakowanie zakończone. Utworzono artefakty ZIP."
artifacts:
  files:
    # Definicja artefaktów do wdrożenia
    - ChapterManager.zip
    - DashboardDataResolver.zip
    - LLM_QueryResolver.zip
