version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20 
    commands:
      # LINIJKA 7 (Commands[0]) MUSI MIEĆ HYFEN I ODPOWIEDNIE WCĘCIE
      - echo "Instalacja: Node.js" 
      - pip install aws-sam-cli 
  
  build:
    commands:
      - echo "Budowanie aplikacji SAM. Automatyczne pakowanie funkcji..."
      - sam build
  
  post_build:
    commands:
      - echo "Wdrażanie do AWS CloudFormation/Lambda..."
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name PlotAss-Backend-Stack --capabilities CAPABILITY_IAM

artifacts:
  files:
    - template.yaml
